name: classroom

services:
  backend:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - USER_ID=${DEVCONTAINER_USER_ID:-1000}
        - USER_NAME=${DEVCONTAINER_USER_NAME:-node}
        - GROUP_ID=${DEVCONTAINER_GROUP_ID:-100}
        - GROUP_NAME=${DEVCONTAINER_GROUP_NAME:-dev}
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      - DATABASE_HOST=database
    depends_on:
      - database
    networks:
      - classroom
    volumes:
      - ..:/akd-studios/classroom/backend

  database:
    image: postgres:16.1-bookworm
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ../.data:/var/lib/postgresql/data
    networks:
      - classroom
    environment:
      - POSTGRES_USER=classroom
      - POSTGRES_PASSWORD=classroom
      - POSTGRES_DB=classroom

networks:
  classroom:
    name: classroom
